### ISSUE TITLE
Stop/Transfer reminder ETA update

### ISSUE THREAD

**Issue by hessianerd** [eddykwang/BartBetter#2]
As someone who likes to read on the train it would be nice to have a "my train" feature which updates arrival times and has a notification for 'this is your stop/transfer point'.  I often get caught up in a book and thus would be extremely helpful.

On a simmilar note.  If I am meeting someone enroute it would be nice to be able to lookup station arrivals for my train to let them know.

**Comment by eddykwang** [comment]
Hey there, thanks for your suggestion, I definitely will consider your idea for the future update. Also feel free to contribute to the project with pull request.
